// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPe-33C-xKAY3omjGOYXCsfei2JyE8flU',
    appId: '1:921100379481:web:606d50ff001a02ce7b1848',
    messagingSenderId: '921100379481',
    projectId: 'news-231e9',
    authDomain: 'news-231e9.firebaseapp.com',
    storageBucket: 'news-231e9.firebasestorage.app',
    measurementId: 'G-JFM2620GF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUPMCkNWkWc4FN6Qh_uoJm4Z_u4VQUcE',
    appId: '1:921100379481:android:f627d49ea09a07287b1848',
    messagingSenderId: '921100379481',
    projectId: 'news-231e9',
    storageBucket: 'news-231e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZyb96VXBvJRSomprSxerJW-fZle4fKmU',
    appId: '1:921100379481:ios:61838b8f13e8f5407b1848',
    messagingSenderId: '921100379481',
    projectId: 'news-231e9',
    storageBucket: 'news-231e9.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZyb96VXBvJRSomprSxerJW-fZle4fKmU',
    appId: '1:921100379481:ios:61838b8f13e8f5407b1848',
    messagingSenderId: '921100379481',
    projectId: 'news-231e9',
    storageBucket: 'news-231e9.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPe-33C-xKAY3omjGOYXCsfei2JyE8flU',
    appId: '1:921100379481:web:25b60f5bf677d1117b1848',
    messagingSenderId: '921100379481',
    projectId: 'news-231e9',
    authDomain: 'news-231e9.firebaseapp.com',
    storageBucket: 'news-231e9.firebasestorage.app',
    measurementId: 'G-9Y62GEEXFM',
  );

}